### ISSUE TITLE
Deploying docs requires ffmpeg installation

### ISSUE THREAD

**Issue by sjvenditto** [flatironinstitute/nemos#229]
The head-direction example requires the ffmpeg to generate the animation. If ffmpeg is installed, deploying the docs after installing nemos with the "docs" dependencies works as-is.  If ffmpeg is not installed, it fails with the error:
```
ERROR   -  Here is a summary of the problems encountered when running the examples

           Unexpected failing examples:
           /Users/svenditto/Documents/nemos/docs/tutorials/plot_02_head_direction.py failed leaving traceback:
           Traceback (most recent call last):
             File "/Users/svenditto/Documents/nemos/docs/tutorials/plot_02_head_direction.py", line 182, in
           <module>
               doc_plots.run_animation(neuron_count, epoch_one_spk.start[0])
             File "/Users/svenditto/Documents/nemos/src/nemos/_documentation_utils/plotting.py", line 506, in
           run_animation
               return HTML(anim.to_html5_video())
                           ^^^^^^^^^^^^^^^^^^^^^
             File "/opt/miniconda3/envs/nemos-test/lib/python3.12/site-packages/matplotlib/animation.py", line
           1265, in to_html5_video
               Writer = writers[mpl.rcParams['animation.writer']]
                        ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             File "/opt/miniconda3/envs/nemos-test/lib/python3.12/site-packages/matplotlib/animation.py", line
           128, in __getitem__
               raise RuntimeError(f"Requested MovieWriter ({name}) not available")
           RuntimeError: Requested MovieWriter (ffmpeg) not available


           -------------------------------------------------------------------------------

Aborted with a BuildError!
```
If there isn't a global ffmpeg installation and if using a conda environment, installing it via conda before pip-installing nemos will also work.

**Comment by billbrod** [comment]
Agreed on avoiding ffmpeg if possible. When you say turn the animation into a gif, what are you thinking?

A possibility is to set `plt.rcParams['animation.html'] = 'jshtml'`, which should work in the browser without anything additional required). 

However, with either the gif or using the jshtml writer, there's the issue of animation size. I don't think there's anyway to give either of them access to any video codec and so you can very easily end up with an absolute massive video. Since we're only using it in this one notebook (rather than providing some general animation tools), we can test it out and make sure it's not too bad, but wanted to flag that. For example, I had a video in plenoptic that was ~40MB when using the jshtml writer, but 320K when using ffmpeg; I think that's because ffmpeg has access to the h264 codec.

(I thought through similar issues [for plenoptic](https://github.com/plenoptic-org/plenoptic/issues/268))

**Comment by BalzaniEdoardo** [comment]
Naively, I was thinking of using pillow for writing the gif form the animation. I have no clue how large it is going to be,  i can try and see the final size and decide

**Comment by billbrod** [comment]
Yes, worth checking that out. There may also be tweaks we can make to the animation to reduce the file size, if it's too large. 

Worth noting that we don't currently require Pillow, so that would also be an additional requirement. (I checked my environment and it's not installed).

I'm also curious if Pillow needs any additional requirements in order to create a gif, like [imagemagick](https://imagemagick.org/), which is how I've created gifs on the command line before)

**Comment by sjvenditto** [comment]
If size is an issue with other animation tools, and if there's plans to have the package conda installable anyway as well as have instructions for creating a conda environment, it might be simple enough to just require an extra line `conda install ffmpeg` before the `pip install`

**Comment by BalzaniEdoardo** [comment]
the size of the animation generated with pillow is 143KB, so that would not be a problem. 

The jshtml solution works, I created a clean env and installed nemos with the "[examples]" optional deps, and run the example with jupyter lab, and it worked with no problem.

The nice fact of a having a gif as asset (writing it) is that the animation would be showing even if the code is run as a python script. Currently, if your run the code in a script, it will show a static figure;

I am still favoring the simplest solution (which is the jshtml setting)

**Comment by billbrod** [comment]
I agree about using jshtml. For the gif, if you're proposing to write the gif and then include it in the docs, a (imo major) downside is that we'd have to update it periodically with any changes. So having the animation generated as part of the docs build is preferable. It's true about running the code as a static script, but in practice I'm not sure how common that will be for users.

**Comment by BalzaniEdoardo** [comment]
Issue fixed in PR #230
